# $FreeBSD: releng/9.2/sys/modules/filemon/Makefile 251504 2013-06-07 19:02:32Z obrien $

.PATH: ${.CURDIR}/../../dev/filemon

KMOD=	filemon
SRCS=	${KMOD}.c
SRCS+=	opt_compat.h

.include <bsd.kmod.mk>
