# $FreeBSD: releng/9.2/usr.sbin/bsdconfig/usermgmt/share/Makefile 252995 2013-07-07 19:13:34Z dteske $

NO_OBJ=

FILESDIR=	${SHAREDIR}/bsdconfig/usermgmt
FILES=		group_input.subr user_input.subr

beforeinstall:
	mkdir -p ${DESTDIR}${FILESDIR}

.include <bsd.prog.mk>
