# $FreeBSD: releng/9.2/usr.sbin/bsdconfig/usermgmt/include/Makefile 252995 2013-07-07 19:13:34Z dteske $

NO_OBJ=

FILESDIR=	${LIBEXECDIR}/bsdconfig/070.usermgmt/include
FILES=		messages.subr usermgmt.hlp

beforeinstall:
	mkdir -p ${DESTDIR}${FILESDIR}

.include <bsd.prog.mk>
