# $FreeBSD: releng/9.2/usr.sbin/bsdconfig/examples/Makefile 252995 2013-07-07 19:13:34Z dteske $

NO_OBJ=

FILESDIR=	${SHAREDIR}/examples/bsdconfig
FILES=		browse_packages.sh bsdconfigrc

beforeinstall:
	mkdir -p ${DESTDIR}${FILESDIR}

.include <bsd.prog.mk>
