# $FreeBSD: releng/9.2/usr.sbin/bsdconfig/ttys/include/Makefile 252995 2013-07-07 19:13:34Z dteske $

NO_OBJ=

FILESDIR=	${LIBEXECDIR}/bsdconfig/150.ttys/include
FILES=		messages.subr

beforeinstall:
	mkdir -p ${DESTDIR}${FILESDIR}

.include <bsd.prog.mk>
