# $FreeBSD: releng/9.2/usr.sbin/sysrc/Makefile 252995 2013-07-07 19:13:34Z dteske $

SCRIPTS= sysrc

MAN= sysrc.8

beforeinstall:
	mkdir -p ${DESTDIR}${SCRIPTSDIR}
	mkdir -p ${DESTDIR}${MANDIR}8

.include <bsd.prog.mk>
