# $FreeBSD: releng/9.2/usr.sbin/bsdconfig/startup/share/Makefile 252995 2013-07-07 19:13:34Z dteske $

NO_OBJ=

FILESDIR=	${SHAREDIR}/bsdconfig/startup
FILES=		rcconf.subr rcedit.subr rcvar.subr

beforeinstall:
	mkdir -p ${DESTDIR}${FILESDIR}

.include <bsd.prog.mk>
