#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: releng/9.2/usr.bin/vis/Makefile 249561 2013-04-16 19:28:00Z brooks $

PROG=	vis
SRCS=	vis.c foldit.c

.PATH: ${.CURDIR}/../../contrib/vis
CFLAGS+=	-I${.CURDIR}/../../contrib/vis

.include <bsd.prog.mk>
