# $FreeBSD: releng/9.2/release/doc/en_US.ISO8859-1/Makefile 251816 2013-06-16 18:59:07Z hrs $

RELN_ROOT?= ${.CURDIR}/..

SUBDIR = relnotes
SUBDIR+= hardware
SUBDIR+= readme
SUBDIR+= errata
SUBDIR+= installation

COMPAT_SYMLINK = en

LANGCODE=en_US.ISO8859-1
_LANGCODE=en_US.ISO8859-1

.include "${RELN_ROOT}/share/mk/doc.relnotes.mk"
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
